### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by cuongvng** [khanhp1406/CoderSchool_Challenge#1]
`What is the job title of JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll).`: chưa cover trường hợp lower case (chữ thường).

**Comment by jkpnk** [comment]
Em đã sửa lại bài rồi, anh vào check giúp em

**Comment by cuongvng** [comment]
ok rồi bạn nhé
